language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: ktran111-github
    token:
      secure: 3600a0f7099cf98e90c226fd0278521e27a85f91 
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
