language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: ktran111-github
    token:
      secure: bea712d8e27f2d80d3fdc0a70e61872b820dcde6 
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
